language: r
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq -y
  - sudo apt-get install -y gcc-4.8
  - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - export CXX="g++-4.8" CC="gcc-4.8"
